# Generated by Django 4.1.4 on 2022-12-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipusers',
            name='ip_user',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
