# Generated by Django 4.1.4 on 2022-12-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_ipusers_ip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipusers',
            name='ip_user',
            field=models.CharField(max_length=32),
        ),
    ]
