# Generated by Django 4.1.4 on 2022-12-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_ipusers_ip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipusers',
            name='user',
        ),
    ]
