# Generated by Django 4.1.4 on 2022-12-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='autor',
        ),
    ]
