# Generated by Django 4.1.4 on 2023-01-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_remove_project_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('flask', 'Flask')], default='python', max_length=10),
        ),
    ]
