# Generated by Django 4.1.4 on 2023-01-03 11:24

from django.db import migrations, models
import projectapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_github',
            field=models.URLField(validators=[projectapp.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_image',
            field=models.URLField(validators=[projectapp.models.validate_url]),
        ),
    ]
